services:
  mt5:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        UPDATE_PACKAGES: "false"
    image: mt5-docker
    container_name: mt5
    volumes:
      - ../config:/config
      - ../data:/data
    ports:
      - 3000:3000
      - 8001:8001
    env_file:
      - .env
    security_opt:
      - seccomp=unconfined
      - label=disable
